Update JavaFX

diff --git a/build/scripts/ConsoleApp b/build/scripts/ConsoleApp
--- a/build/scripts/ConsoleApp
+++ b/build/scripts/ConsoleApp
@@ -55,7 +55,7 @@
 #       Darwin, MinGW, and NonStop.
 #
 #   (3) This script is generated from the Groovy template
-#       https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
+#       https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
 #       within the Gradle project.
 #
 #       You can find Gradle at https://github.com/gradle/gradle/.
@@ -80,13 +80,10 @@ do
     esac
 done
 
-APP_HOME=$( cd "${APP_HOME:-./}.." && pwd -P ) || exit
-
-APP_NAME="ConsoleApp"
+# This is normally unused
+# shellcheck disable=SC2034
 APP_BASE_NAME=${0##*/}
-
-# Add default JVM options here. You can also use JAVA_OPTS and CONSOLE_APP_OPTS to pass JVM options to this script.
-DEFAULT_JVM_OPTS=""
+APP_HOME=$( cd "${APP_HOME:-./}.." && pwd -P ) || exit
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
 MAX_FD=maximum
@@ -114,7 +111,7 @@ case "$( uname )" in                #(
   NONSTOP* )        nonstop=true ;;
 esac
 
-CLASSPATH=$APP_HOME/lib/ConsoleApp-1.0.jar:$APP_HOME/lib/javafx-fxml-17.0.1-win.jar:$APP_HOME/lib/javafx-controls-17.0.1-win.jar:$APP_HOME/lib/javafx-controls-17.0.1.jar:$APP_HOME/lib/javafx-graphics-17.0.1-win.jar:$APP_HOME/lib/javafx-graphics-17.0.1.jar:$APP_HOME/lib/javafx-base-17.0.1-win.jar:$APP_HOME/lib/javafx-base-17.0.1.jar:$APP_HOME/lib/annotations-20.1.0.jar:$APP_HOME/lib/postgresql-42.3.1.jar:$APP_HOME/lib/checker-qual-3.5.0.jar
+CLASSPATH=$APP_HOME/lib/ConsoleApp-1.0.jar:$APP_HOME/lib/javafx-fxml-17.0.1-linux.jar:$APP_HOME/lib/javafx-controls-17.0.1-linux.jar:$APP_HOME/lib/javafx-controls-17.0.1.jar:$APP_HOME/lib/javafx-graphics-17.0.1-linux.jar:$APP_HOME/lib/javafx-graphics-17.0.1.jar:$APP_HOME/lib/javafx-base-17.0.1-linux.jar:$APP_HOME/lib/javafx-base-17.0.1.jar:$APP_HOME/lib/annotations-20.1.0.jar:$APP_HOME/lib/postgresql-42.3.1.jar:$APP_HOME/lib/checker-qual-3.5.0.jar
 
 
 # Determine the Java command to use to start the JVM.
@@ -133,22 +130,29 @@ location of your Java installation."
     fi
 else
     JAVACMD=java
-    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+    if ! command -v java >/dev/null 2>&1
+    then
+        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
 
 Please set the JAVA_HOME variable in your environment to match the
 location of your Java installation."
+    fi
 fi
 
 # Increase the maximum file descriptors if we can.
 if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
     case $MAX_FD in #(
       max*)
+        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
+        # shellcheck disable=SC3045
         MAX_FD=$( ulimit -H -n ) ||
             warn "Could not query maximum file descriptor limit"
     esac
     case $MAX_FD in  #(
       '' | soft) :;; #(
       *)
+        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
+        # shellcheck disable=SC3045
         ulimit -n "$MAX_FD" ||
             warn "Could not set maximum file descriptor limit to $MAX_FD"
     esac
@@ -193,6 +197,10 @@ if "$cygwin" || "$msys" ; then
     done
 fi
 
+
+# Add default JVM options here. You can also use JAVA_OPTS and CONSOLE_APP_OPTS to pass JVM options to this script.
+DEFAULT_JVM_OPTS=""
+
 # Collect all arguments for the java command;
 #   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $CONSOLE_APP_OPTS can contain fragments of
 #     shell script including quotes and variable substitutions, so put them in
@@ -203,6 +211,12 @@ set -- \
         -classpath "$CLASSPATH" \
         Main \
         "$@"
+
+# Stop when "xargs" is not available.
+if ! command -v xargs >/dev/null 2>&1
+then
+    die "xargs is not available"
+fi
 
 # Use "xargs" to parse quoted args.
 #
